from braincube import connector
from datetime import datetime

row = connector.connect(format_type='raw')
pandas = connector.connect()
print("\nget bc list")
print(pandas.get_braincube_list())
print(row.get_braincube_list())
print("\nget mb list")
print(pandas.get_memorybase_list('axone'))
print(row.get_memorybase_list('axone'))
print("\nget mb refs")
print(pandas.get_memorybase_order_variable('axone', 18))
print(row.get_memorybase_references('axone', 18))
print("\nget var list")
print(pandas.get_variable_list('axone', 18))
print(row.get_variable_list('axone', 18))
print("\nretrieve all var")
print(pandas.retrieve_data('axone', 18, [1800002, 1800003, 1800098], datetime(2018, 5, 22), datetime(2018, 5, 23)))
print(row.retrieve_data('axone', 18, [1800002, 1800003, 1800098], datetime(2018, 5, 22), datetime(2018, 5, 23)))
print("\ntest objects")
mbp = pandas.create_memorybase('axone', 18)
mbr = row.create_memorybase('axone', 18)
print(mbp.get_variable_list())
print(mbr.get_variable_list())
print(connector.retrieve_data_from_web())
